// Перевод названий предметов ТГЭУ (узбекский → русский / английский).
// Используется для расписания с EduPage и для названий, которые HEMIS не перевёл.
// Ключ сравнивается без регистра, апострофов, дефисов и номера части («Moliyaviy hisob-1» → «Moliyaviy hisob» + « 1»).
"use strict";

const SUBJECTS_RAW = [
  ["Agrologistika", "Агрологистика", "Agrologistics"],
  ["Akademik ko'nikmalar va kasbiy kompetentlik", "Академические навыки и профессиональная компетентность", "Academic Skills and Professional Competence"],
  ["Akademik yozuv", "Академическое письмо", "Academic Writing"],
  ["Amaliy audit", "Практический аудит", "Applied Auditing"],
  ["Amaliy ekonometrika", "Прикладная эконометрика", "Applied Econometrics"],
  ["Amaliy intellektual tizimlari", "Прикладные интеллектуальные системы", "Applied Intelligent Systems"],
  ["Amaliy matematika", "Прикладная математика", "Applied Mathematics"],
  ["Amaliy statistika", "Прикладная статистика", "Applied Statistics"],
  ["Atrof muhit iqtisodiyoti va iqlim o'zgarishi", "Экономика окружающей среды и изменение климата", "Environmental Economics and Climate Change"],
  ["Audit", "Аудит", "Auditing"],
  ["Audit va turdosh xizmatlar", "Аудит и сопутствующие услуги", "Audit and Related Services"],
  ["Auditga kirish", "Введение в аудит", "Introduction to Auditing"],
  ["Auditning dolzarb masalalari", "Актуальные вопросы аудита", "Current Issues in Auditing"],
  ["Auditning xalqaro standartlari", "Международные стандарты аудита", "International Standards on Auditing"],
  ["Auditorning kasb etikasi", "Профессиональная этика аудитора", "Professional Ethics of Auditors"],
  ["Axborot tiz. ishlab chiqarish metodologiyalari", "Методологии разработки информационных систем", "Information Systems Development Methodologies"],
  ["Axborot tizimini ishlab chiqarish metodologiyalari", "Методологии разработки информационных систем", "Information Systems Development Methodologies"],
  ["Axborot texnologiyalari", "Информационные технологии", "Information Technology"],
  ["B2B marketing", "B2B-маркетинг", "B2B Marketing"],
  ["Baholash ishi", "Оценочная деятельность", "Valuation Practice"],
  ["Bank auditi metodologiyasi", "Методология банковского аудита", "Bank Audit Methodology"],
  ["Bank ishi", "Банковское дело", "Banking"],
  ["Bank menejmenti", "Банковский менеджмент", "Bank Management"],
  ["Banklarda buxgalteriya hisobi", "Бухгалтерский учёт в банках", "Accounting in Banks"],
  ["Banklarda buxgalteriay hisobi", "Бухгалтерский учёт в банках", "Accounting in Banks"],
  ["Banklarda korporativ boshqaruv", "Корпоративное управление в банках", "Corporate Governance in Banks"],
  ["Banklarda moliyaviy hisob", "Финансовый учёт в банках", "Financial Accounting in Banks"],
  ["Banklarda risk menejment", "Риск-менеджмент в банках", "Risk Management in Banks"],
  ["Barqaror biznes strategiyasi", "Стратегия устойчивого бизнеса", "Sustainable Business Strategy"],
  ["Barqaror o'sish va tengsizlik", "Устойчивый рост и неравенство", "Sustainable Growth and Inequality"],
  ["Barqaror turizm rivojlanishi", "Устойчивое развитие туризма", "Sustainable Tourism Development"],
  ["Big Data va Data Mining", "Big Data и Data Mining", "Big Data and Data Mining"],
  ["Biznes analitika", "Бизнес-аналитика", "Business Analytics"],
  ["Biznes asoslari", "Основы бизнеса", "Business Fundamentals"],
  ["Biznes huquqi", "Предпринимательское право", "Business Law"],
  ["Biznes intellekt tizimlari", "Системы бизнес-аналитики (BI)", "Business Intelligence Systems"],
  ["Biznes kommunikatsiya", "Деловая коммуникация", "Business Communication"],
  ["Biznes psixologiya", "Психология бизнеса", "Business Psychology"],
  ["Biznes statistika", "Бизнес-статистика", "Business Statistics"],
  ["Biznes strategiya", "Бизнес-стратегия", "Business Strategy"],
  ["Biznes strategiyasi", "Бизнес-стратегия", "Business Strategy"],
  ["Biznes tahlil", "Бизнес-анализ", "Business Analysis"],
  ["Biznesda buxgalteriya hisobi", "Бухгалтерский учёт в бизнесе", "Accounting in Business"],
  ["Biznesni tadqiq etish usullari", "Методы бизнес-исследований", "Business Research Methods"],
  ["Blokchain va taqsimlangan reestr tex.", "Блокчейн и технологии распределённого реестра", "Blockchain and Distributed Ledger Technologies"],
  ["Blokcheyn va markazlashmagan Internet", "Блокчейн и децентрализованный интернет", "Blockchain and the Decentralized Internet"],
  ["Bojxona ishi", "Таможенное дело", "Customs Affairs"],
  ["Bojxona isloxatlari va moderinizatsiya", "Таможенные реформы и модернизация", "Customs Reforms and Modernization"],
  ["Bojxona rasmiylashtiruvi", "Таможенное оформление", "Customs Clearance"],
  ["Boshqa tarmoqlarda buxgalteriya hisobi", "Бухгалтерский учёт в других отраслях", "Accounting in Other Industries"],
  ["Boshqa tarmoqlarda buxgalteriya hisobining xususiyatlari", "Особенности бухгалтерского учёта в других отраслях", "Specifics of Accounting in Other Industries"],
  ["Boshqa tarmoqlarda buxgalteriya hisobining hususiyatlari", "Особенности бухгалтерского учёта в других отраслях", "Specifics of Accounting in Other Industries"],
  ["Boshqa tarmoqlarda buxgalteriya hisboning xusussiyatlari", "Особенности бухгалтерского учёта в других отраслях", "Specifics of Accounting in Other Industries"],
  ["Boshqaruv axborot tizimlar", "Управленческие информационные системы", "Management Information Systems"],
  ["Boshqaruv axborot tizimlari", "Управленческие информационные системы", "Management Information Systems"],
  ["Boshqaruv hisobi", "Управленческий учёт", "Management Accounting"],
  ["Boshqaruv moliyasi", "Управленческие финансы", "Managerial Finance"],
  ["Boshqaruv psixologiyasi", "Психология управления", "Management Psychology"],
  ["Brend qiymatini yaratish", "Создание ценности бренда", "Brand Value Creation"],
  ["Brendni boshqarish", "Управление брендом", "Brand Management"],
  ["Bulutli texnologiyalar", "Облачные технологии", "Cloud Technologies"],
  ["Buxgalteriya hisobi", "Бухгалтерский учёт", "Accounting"],
  ["Buxgalteriya hisobi tadqiqot usullari", "Методы исследований в бухгалтерском учёте", "Accounting Research Methods"],
  ["Buxgalteriya hisobi va audit", "Бухгалтерский учёт и аудит", "Accounting and Auditing"],
  ["Buxgalteriya hisobida ICT", "ИКТ в бухгалтерском учёте", "ICT in Accounting"],
  ["Buxgalteriya hisobida raqamli transformatsiya", "Цифровая трансформация бухгалтерского учёта", "Digital Transformation in Accounting"],
  ["Buxgalteriya hisobiga kirish", "Введение в бухгалтерский учёт", "Introduction to Accounting"],
  ["Buxgalteriya, tashkilotlar va jamiyat", "Бухгалтерский учёт, организации и общество", "Accounting, Organizations and Society"],
  ["Buyumlar interneti", "Интернет вещей", "Internet of Things"],
  ["Byudjet tashkilotlarida ichki audit", "Внутренний аудит в бюджетных организациях", "Internal Audit in Budgetary Organizations"],
  ["Chiziqli algebra", "Линейная алгебра", "Linear Algebra"],
  ["CRM marketing", "CRM-маркетинг", "CRM Marketing"],
  ["Dasturiy injenering", "Программная инженерия", "Software Engineering"],
  ["Dasturlash", "Программирование", "Programming"],
  ["Davlat moliyasi", "Государственные финансы", "Public Finance"],
  ["Davlat moliyaviy nazorati", "Государственный финансовый контроль", "State Financial Control"],
  ["Davlat organlarida xavflarni boshqarish", "Управление рисками в государственных органах", "Risk Management in Public Authorities"],
  ["Davlat qarz siyosati", "Государственная долговая политика", "Public Debt Policy"],
  ["Davlat sektorida buxgalteriya hisobi va hisoboti", "Бухгалтерский учёт и отчётность в государственном секторе", "Public Sector Accounting and Reporting"],
  ["Davlat sektorida buxgalteriya hisobining xalqaro standartlari", "Международные стандарты учёта в государственном секторе (МСФО ОС)", "International Public Sector Accounting Standards (IPSAS)"],
  ["Davlat sektorida korporativ boshqaruv", "Корпоративное управление в государственном секторе", "Corporate Governance in the Public Sector"],
  ["Davlat sektorida tashqi audit", "Внешний аудит в государственном секторе", "External Audit in the Public Sector"],
  ["Davlat xaridlari", "Государственные закупки", "Public Procurement"],
  ["Davlatning iqtisodiy siyosati", "Экономическая политика государства", "State Economic Policy"],
  ["Davlatning iqtisodiy xavfsizligi", "Экономическая безопасность государства", "Economic Security of the State"],
  ["Demografiya asoslari", "Основы демографии", "Fundamentals of Demography"],
  ["Dinshunoslik", "Религиоведение", "Religious Studies"],
  ["Diplomatiya va biznes etiket", "Дипломатия и деловой этикет", "Diplomacy and Business Etiquette"],
  ["Diskret tuzilmalar", "Дискретные структуры", "Discrete Structures"],
  ["Ekologik menejment", "Экологический менеджмент", "Environmental Management"],
  ["Ekonometrika", "Эконометрика", "Econometrics"],
  ["Ekonometrikaga kirish", "Введение в эконометрику", "Introduction to Econometrics"],
  ["Elektron tijorat", "Электронная коммерция", "E-commerce"],
  ["Elektron tijorat va zamonaviy axborot texnologiyalar", "Электронная коммерция и современные информационные технологии", "E-commerce and Modern Information Technologies"],
  ["Elektronika va sxema", "Электроника и схемотехника", "Electronics and Circuits"],
  ["Empirik moliya", "Эмпирические финансы", "Empirical Finance"],
  ["Falsafa", "Философия", "Philosophy"],
  ["Fiskal siyosat makroiqtisodiy yondashuv", "Фискальная политика: макроэкономический подход", "Fiscal Policy: A Macroeconomic Approach"],
  ["Fizika", "Физика", "Physics"],
  ["Gastronomiya", "Гастрономия", "Gastronomy"],
  ["Global biznes muhit", "Глобальная бизнес-среда", "Global Business Environment"],
  ["Global iqlim o'zgarishi", "Глобальное изменение климата", "Global Climate Change"],
  ["Global iqtisodiy rivojlanish", "Глобальное экономическое развитие", "Global Economic Development"],
  ["Global iqtisodiyot va hududiy rivojlanish", "Глобальная экономика и региональное развитие", "Global Economy and Regional Development"],
  ["Global migratsiya va demografiya", "Глобальная миграция и демография", "Global Migration and Demography"],
  ["Global siyosiy iqtisodiyot", "Глобальная политическая экономия", "Global Political Economy"],
  ["Hayot faoliyati xavfsizligi", "Безопасность жизнедеятельности", "Life Safety"],
  ["Hisob (Calculus)", "Математический анализ", "Calculus"],
  ["HR auditi va konsaltingi", "HR-аудит и консалтинг", "HR Audit and Consulting"],
  ["HR byudjeti", "HR-бюджетирование", "HR Budgeting"],
  ["IAKT", "ИКТ в экономике", "ICT in Economics"],
  ["IAKTT", "Информационно-коммуникационные технологии и системы в экономике", "ICT and Systems in Economics"],
  ["Ichki audit", "Внутренний аудит", "Internal Audit"],
  ["Ijro menejmenti", "Исполнительский менеджмент", "Executive Management"],
  ["Ijtimoiy himoya moliyasi", "Финансы социальной защиты", "Social Protection Finance"],
  ["Ijtimoiy psixologiya", "Социальная психология", "Social Psychology"],
  ["Ilmiy tadqiqot metodologiyasi", "Методология научных исследований", "Research Methodology"],
  ["Infratuzilma iqtisodiyoti", "Экономика инфраструктуры", "Infrastructure Economics"],
  ["Ingliz tili", "Английский язык", "English"],
  ["Innovatsion menejment va tadbirkorlik", "Инновационный менеджмент и предпринимательство", "Innovation Management and Entrepreneurship"],
  ["Inson resurslarini boshqarish", "Управление человеческими ресурсами", "Human Resource Management"],
  ["Inson resurslarini strategik boshqarish", "Стратегическое управление человеческими ресурсами", "Strategic Human Resource Management"],
  ["Inson taraqqiyoti", "Человеческое развитие", "Human Development"],
  ["Inson taraqiyoti", "Человеческое развитие", "Human Development"],
  ["Institutsional iqtisodiyot", "Институциональная экономика", "Institutional Economics"],
  ["Internet marketing", "Интернет-маркетинг", "Internet Marketing"],
  ["Internet reklama va marketing", "Интернет-реклама и маркетинг", "Internet Advertising and Marketing"],
  ["Investitsion banklar", "Инвестиционные банки", "Investment Banks"],
  ["Investitsiya", "Инвестиции", "Investments"],
  ["Investitsiya loyihalari ekspertizasi", "Экспертиза инвестиционных проектов", "Investment Project Appraisal"],
  ["Investitsiya loyihalari tahlili", "Анализ инвестиционных проектов", "Investment Project Analysis"],
  ["Investitsiya loyihalarini boshqarish", "Управление инвестиционными проектами", "Investment Project Management"],
  ["Investitsiya siyosati", "Инвестиционная политика", "Investment Policy"],
  ["Investitsiyalarni iqtisodiy baholash", "Экономическая оценка инвестиций", "Economic Evaluation of Investments"],
  ["Iqtisodiy ma'lumotlar tahlili", "Анализ экономических данных", "Economic Data Analysis"],
  ["Iqtisodiy o'sish", "Экономический рост", "Economic Growth"],
  ["Iqtisodiy siyosat", "Экономическая политика", "Economic Policy"],
  ["Iqtisodiy tahlil", "Экономический анализ", "Economic Analysis"],
  ["Iqtisodiy ta'limotlar tarixi", "История экономических учений", "History of Economic Thought"],
  ["Iqtisodiy taraqqiyot strategiyalari", "Стратегии экономического развития", "Economic Development Strategies"],
  ["Iqtisodiy xavfsizlik", "Экономическая безопасность", "Economic Security"],
  ["Iqtisodiy xavfsizligi", "Экономическая безопасность", "Economic Security"],
  ["Iqtisodiy xavfsizlikning tahlil usullari", "Методы анализа экономической безопасности", "Methods of Economic Security Analysis"],
  ["Iqtisodiyot", "Экономика", "Economics"],
  ["Iqtisodiyot nazariyasi", "Экономическая теория", "Economic Theory"],
  ["Iqtisodiyot, bozor va savdo", "Экономика, рынок и торговля", "Economics, Markets and Trade"],
  ["Iqtisodiyotda axborot-kommunikatsion texnologiyalar va tizimlar", "Информационно-коммуникационные технологии и системы в экономике", "Information and Communication Technologies and Systems in Economics"],
  ["Iqtisodiyotda ma'lumotlar tahlili", "Анализ данных в экономике", "Data Analysis in Economics"],
  ["Ishga yollash strategiyasi", "Стратегия найма персонала", "Recruitment Strategy"],
  ["Ishlab chiqarish menejmenti", "Производственный менеджмент", "Production Management"],
  ["Islom moliyasi", "Исламские финансы", "Islamic Finance"],
  ["Islomiy moliya", "Исламские финансы", "Islamic Finance"],
  ["Islomiy moliya shartnomalari", "Договоры исламского финансирования", "Islamic Finance Contracts"],
  ["Iste'molchi xulq atvori", "Поведение потребителей", "Consumer Behavior"],
  ["Istemolchi dahlsizligi va xizmat sifatini boshqarish", "Защита прав потребителей и управление качеством услуг", "Consumer Protection and Service Quality Management"],
  ["Istiqbolli kasblar", "Перспективные профессии", "Promising Professions"],
  ["IT audit", "ИТ-аудит", "IT Audit"],
  ["IT loyiha boshqaruvi", "Управление ИТ-проектами", "IT Project Management"],
  ["Jahon iqtisodiyoti", "Мировая экономика", "World Economy"],
  ["Jismoniy madaniyat va sport", "Физическая культура и спорт", "Physical Education and Sports"],
  ["Jismoniy tarbiya va sport", "Физическое воспитание и спорт", "Physical Education and Sports"],
  ["Kapital bozori", "Рынок капитала", "Capital Market"],
  ["Karyerani boshqarish va kasbiy rivojlanish", "Управление карьерой и профессиональное развитие", "Career Management and Professional Development"],
  ["Kelajak soati", "Час будущего", "Hour of the Future"],
  ["Ko'nikmaga asoslangan ta'lim", "Обучение на основе навыков", "Skills-Based Learning"],
  ["Ko'nikmaga asoslangan ta'lim (soft skills)", "Обучение на основе навыков (soft skills)", "Skills-Based Learning (Soft Skills)"],
  ["Kompyuter tarmoqlari", "Компьютерные сети", "Computer Networks"],
  ["Kompyuterli ko'rish", "Компьютерное зрение", "Computer Vision"],
  ["Kongress va tadbirlarni tashkillashtirish", "Организация конгрессов и мероприятий", "Congress and Event Management"],
  ["Korporativ boshqaruv", "Корпоративное управление", "Corporate Governance"],
  ["Korporativ ijtimoiy ma'suliyat", "Корпоративная социальная ответственность", "Corporate Social Responsibility"],
  ["Korporativ moliya", "Корпоративные финансы", "Corporate Finance"],
  ["Korporativ moliya strategiyasi", "Стратегия корпоративных финансов", "Corporate Finance Strategy"],
  ["Korporativ moliyaviy xisobot", "Корпоративная финансовая отчётность", "Corporate Financial Reporting"],
  ["Korporativ risklarni boshqarish", "Управление корпоративными рисками", "Corporate Risk Management"],
  ["Korporativ soliqlarni rejalashtirish", "Корпоративное налоговое планирование", "Corporate Tax Planning"],
  ["Korxona iqtisodiy xavfsizligi", "Экономическая безопасность предприятия", "Enterprise Economic Security"],
  ["Korxona iqtisodiyoti", "Экономика предприятия", "Enterprise Economics"],
  ["Korxona resurslarinin rejalashtirish (ERP tizimlari)", "Планирование ресурсов предприятия (ERP-системы)", "Enterprise Resource Planning (ERP Systems)"],
  ["Korxonalarni rivojlantirish strstegiyasi", "Стратегия развития предприятий", "Enterprise Development Strategy"],
  ["Kriptografiya usullari", "Методы криптографии", "Cryptographic Methods"],
  ["Liderlik", "Лидерство", "Leadership"],
  ["Liderlik va tashkiliy kommunikatsiya", "Лидерство и организационная коммуникация", "Leadership and Organizational Communication"],
  ["Logistika", "Логистика", "Logistics"],
  ["Logistika asoslari", "Основы логистики", "Fundamentals of Logistics"],
  ["Logistika va elektron tijorat", "Логистика и электронная коммерция", "Logistics and E-commerce"],
  ["Logistikani boshqarish", "Управление логистикой", "Logistics Management"],
  ["Loyiha boshqaruvi", "Управление проектами", "Project Management"],
  ["Loyihalarni boshqarish", "Управление проектами", "Project Management"],
  ["Loyiha yaratish va raqamli startap", "Создание проектов и цифровой стартап", "Project Creation and Digital Startups"],
  ["Ma'lumotlar bazasi xavfsizligi", "Безопасность баз данных", "Database Security"],
  ["Ma'lumotlar bazalari", "Базы данных", "Databases"],
  ["Ma'lumotlar bazasi", "Базы данных", "Databases"],
  ["Ma'lumotlarni tahlil qilish va vizualizatsiya", "Анализ и визуализация данных", "Data Analysis and Visualization"],
  ["Ma'rifat darsi", "Урок просвещения", "Enlightenment Lesson"],
  ["Mahalliy salohiyat va iqtisodiy rivojlanish siyosati", "Местный потенциал и политика экономического развития", "Local Capacity and Economic Development Policy"],
  ["Makroiqtisodiy tahlil va prog.", "Макроэкономический анализ и прогнозирование", "Macroeconomic Analysis and Forecasting"],
  ["Makroiqtisodiyot", "Макроэкономика", "Macroeconomics"],
  ["Marketing", "Маркетинг", "Marketing"],
  ["Marketing analitikasi", "Маркетинговая аналитика", "Marketing Analytics"],
  ["Marketing menejment", "Маркетинг-менеджмент", "Marketing Management"],
  ["Marketing strategiyasi modellari", "Модели маркетинговой стратегии", "Marketing Strategy Models"],
  ["Marketingda loyihalar", "Проекты в маркетинге", "Marketing Projects"],
  ["Mashinali o'qitishga kirish", "Введение в машинное обучение", "Introduction to Machine Learning"],
  ["Matematik iqtisodiyot", "Математическая экономика", "Mathematical Economics"],
  ["Matnlarni tanlab olish axb. qidirish", "Интеллектуальный анализ текстов и информационный поиск", "Text Mining and Information Retrieval"],
  ["Maxsus fanlarni o'qitish metodikasi", "Методика преподавания специальных дисциплин", "Methods of Teaching Specialized Subjects"],
  ["Maxsus kurs", "Спецкурс", "Special Course"],
  ["Mehmondo'stlik industriyasi", "Индустрия гостеприимства", "Hospitality Industry"],
  ["Mehmonxona dizayni", "Дизайн гостиниц", "Hotel Design"],
  ["Mehmonxona va restoran menejmenti", "Гостиничный и ресторанный менеджмент", "Hotel and Restaurant Management"],
  ["Mehnat iqtisodiyoti", "Экономика труда", "Labor Economics"],
  ["Mehnat munosabatlari va huquqi", "Трудовые отношения и трудовое право", "Labor Relations and Labor Law"],
  ["Menejment", "Менеджмент", "Management"],
  ["Menejmentning tadqiqot usullari", "Методы исследования в менеджменте", "Management Research Methods"],
  ["Merchendayzing", "Мерчандайзинг", "Merchandising"],
  ["Mikroiqtisodiyot", "Микроэкономика", "Microeconomics"],
  ["Milliy va mintaqaviy iqtisodiy xavfsizlik", "Национальная и региональная экономическая безопасность", "National and Regional Economic Security"],
  ["Mintaqaviy iqtisodiyot", "Региональная экономика", "Regional Economics"],
  ["Mintaqaviy turizm resurslari", "Региональные туристские ресурсы", "Regional Tourism Resources"],
  ["Moliya", "Финансы", "Finance"],
  ["Moliya asoslari", "Основы финансов", "Fundamentals of Finance"],
  ["Moliyaviy boshqaruv hisobi", "Финансово-управленческий учёт", "Financial Management Accounting"],
  ["Moliyaviy hisob", "Финансовый учёт", "Financial Accounting"],
  ["Moliyaviy hisobot", "Финансовая отчётность", "Financial Reporting"],
  ["Moliyaviy hisobot auditi", "Аудит финансовой отчётности", "Audit of Financial Statements"],
  ["Moliyaviy hisobot tahlili", "Анализ финансовой отчётности", "Financial Statement Analysis"],
  ["Moliyaviy hisobotlarning xalqaro standartlari", "Международные стандарты финансовой отчётности (МСФО)", "International Financial Reporting Standards (IFRS)"],
  ["Moliyaviy inqirozlar", "Финансовые кризисы", "Financial Crises"],
  ["Moliyaviy iqtisodiyot", "Финансовая экономика", "Financial Economics"],
  ["Moliyaviy menejment", "Финансовый менеджмент", "Financial Management"],
  ["Moliyaviy nazorat", "Финансовый контроль", "Financial Control"],
  ["Moliyaviy risklar", "Финансовые риски", "Financial Risks"],
  ["Moliyaviy risklarni boshqarish", "Управление финансовыми рисками", "Financial Risk Management"],
  ["Moliyaviy tahlil", "Финансовый анализ", "Financial Analysis"],
  ["Moliyaviy tizimlar va inqirozlar", "Финансовые системы и кризисы", "Financial Systems and Crises"],
  ["Monetar nazariya va siyosat", "Монетарная теория и политика", "Monetary Theory and Policy"],
  ["Monetar siyosat", "Монетарная политика", "Monetary Policy"],
  ["Monetar siyosat makroiqtisodiy yondashuv", "Монетарная политика: макроэкономический подход", "Monetary Policy: A Macroeconomic Approach"],
  ["Muqobil investitsiyalar", "Альтернативные инвестиции", "Alternative Investments"],
  ["Mustaqil ta'lim", "Самостоятельное обучение", "Independent Study"],
  ["Mustaqillik darsi", "Урок независимости", "Independence Lesson"],
  ["Neyromarketing", "Нейромаркетинг", "Neuromarketing"],
  ["Oliy matematika", "Высшая математика", "Higher Mathematics"],
  ["O'zbekiston Resp.soliq tizimi", "Налоговая система Республики Узбекистан", "Tax System of the Republic of Uzbekistan"],
  ["O'zbekiston Respiblikasi soliq tizimi", "Налоговая система Республики Узбекистан", "Tax System of the Republic of Uzbekistan"],
  ["O'zbekiston Respublikasi soliq tizimi", "Налоговая система Республики Узбекистан", "Tax System of the Republic of Uzbekistan"],
  ["O'zbekistonning eng yangi tarixi", "Новейшая история Узбекистана", "Contemporary History of Uzbekistan"],
  ["O'zbekiston sug'urta bozori", "Страховой рынок Узбекистана", "Insurance Market of Uzbekistan"],
  ["Oilaviy tadbirkorlik", "Семейное предпринимательство", "Family Entrepreneurship"],
  ["Omborxona logistikasi", "Складская логистика", "Warehouse Logistics"],
  ["Operatsion jarayonlar", "Операционные процессы", "Operational Processes"],
  ["Operatsion menejment", "Операционный менеджмент", "Operations Management"],
  ["Operatsion tizim xavfsizligi", "Безопасность операционных систем", "Operating System Security"],
  ["Oraliq boshqaruv hisobi", "Управленческий учёт (продвинутый уровень)", "Intermediate Management Accounting"],
  ["O'zbek / Rus tili", "Узбекский / русский язык", "Uzbek / Russian Language"],
  ["O'zbek tili", "Узбекский язык", "Uzbek Language"],
  ["PR menejmenti", "PR-менеджмент", "PR Management"],
  ["Professional buxgalteriya amaliyoti", "Профессиональная бухгалтерская практика", "Professional Accounting Practice"],
  ["Prognozlashning amaliy usullari", "Прикладные методы прогнозирования", "Applied Forecasting Methods"],
  ["Pul va banklar", "Деньги и банки", "Money and Banking"],
  ["Pul va kredit", "Деньги и кредит", "Money and Credit"],
  ["Qaror qabul qilishda ko'mak/tizim", "Системы поддержки принятия решений", "Decision Support Systems"],
  ["Qayta sug'urta", "Перестрахование", "Reinsurance"],
  ["Qimmatli qog'ozlar qiymatini baholash", "Оценка стоимости ценных бумаг", "Securities Valuation"],
  ["R dasturida ma'lumotlar tahlili", "Анализ данных в R", "Data Analysis in R"],
  ["Raqamli bank ishi", "Цифровой банкинг", "Digital Banking"],
  ["Raqamli biznesni boshqarish", "Управление цифровым бизнесом", "Digital Business Management"],
  ["Raqamli iqtisodiyot", "Цифровая экономика", "Digital Economy"],
  ["Raqamli iqtisodiyotning mikro va makro istiqbollari", "Микро- и макроперспективы цифровой экономики", "Micro and Macro Perspectives of the Digital Economy"],
  ["Raqamli marketing", "Цифровой маркетинг", "Digital Marketing"],
  ["Raqamli marketing ijtimoiy media va platformalar", "Цифровой маркетинг: социальные сети и платформы", "Digital Marketing: Social Media and Platforms"],
  ["Raqamli moliya", "Цифровые финансы", "Digital Finance"],
  ["Raqamli sug'urta texnologiyalari", "Цифровые технологии страхования", "Digital Insurance Technologies"],
  ["Reklama ishi", "Рекламное дело", "Advertising"],
  ["Reklama menejmenti", "Рекламный менеджмент", "Advertising Management"],
  ["Reverse Engineering", "Обратная разработка", "Reverse Engineering"],
  ["Risk menejmenti", "Риск-менеджмент", "Risk Management"],
  ["Risklarni moliyalashtirish", "Финансирование рисков", "Risk Financing"],
  ["Rivojlangan davlatlarda bojxona ishi", "Таможенное дело в развитых странах", "Customs Affairs in Developed Countries"],
  ["Rivojlanish siyosati asoslari", "Основы политики развития", "Fundamentals of Development Policy"],
  ["Rus tili", "Русский язык", "Russian Language"],
  ["Sanoat iqtisodiyoti", "Экономика промышленности", "Industrial Economics"],
  ["Sanoat-4,0 va ijtimoiy soha-5,0", "Индустрия 4.0 и социальная сфера 5.0", "Industry 4.0 and Society 5.0"],
  ["Savdo faoliyatini raqamli transformatsiyalash", "Цифровая трансформация торговой деятельности", "Digital Transformation of Trade"],
  ["Savdo statistikasi", "Статистика торговли", "Trade Statistics"],
  ["Sifat va raqobatbardoshlikni boshqarish", "Управление качеством и конкурентоспособностью", "Quality and Competitiveness Management"],
  ["Soft skills", "Гибкие навыки (soft skills)", "Soft Skills"],
  ["Soliq huquqi", "Налоговое право", "Tax Law"],
  ["Soliq maslahati", "Налоговое консультирование", "Tax Consulting"],
  ["Soliq risklari va ularni boshqarish", "Налоговые риски и управление ими", "Tax Risks and Their Management"],
  ["Soliq siyosati", "Налоговая политика", "Tax Policy"],
  ["Soliq tizimida dasturiy mahsullar", "Программные продукты в налоговой системе", "Software Products in the Tax System"],
  ["Soliq tizimining islohotlari va taraqqiyoti", "Реформы и развитие налоговой системы", "Tax System Reforms and Development"],
  ["Soliq tushumlarini prognozlash", "Прогнозирование налоговых поступлений", "Tax Revenue Forecasting"],
  ["Soliq va soliqqa tortish", "Налоги и налогообложение", "Taxes and Taxation"],
  ["Soliqlar va soliqqa tortish", "Налоги и налогообложение", "Taxes and Taxation"],
  ["Soliqqa kirish", "Введение в налогообложение", "Introduction to Taxation"],
  ["Sotuvni boshqarish", "Управление продажами", "Sales Management"],
  ["Statistik baholash", "Статистическое оценивание", "Statistical Estimation"],
  ["Statistik modellashtirish", "Статистическое моделирование", "Statistical Modeling"],
  ["Statistika", "Статистика", "Statistics"],
  ["Statistika nazariyasi", "Теория статистики", "Theory of Statistics"],
  ["Strategik boshqaruv xisobi", "Стратегический управленческий учёт", "Strategic Management Accounting"],
  ["Strategik marketing", "Стратегический маркетинг", "Strategic Marketing"],
  ["Strategik menejment", "Стратегический менеджмент", "Strategic Management"],
  ["Strategik rejalashtirish va boshqarish", "Стратегическое планирование и управление", "Strategic Planning and Management"],
  ["Sug'urta bozori tahlili", "Анализ страхового рынка", "Insurance Market Analysis"],
  ["Sug'urtada aktuar hisoblar", "Актуарные расчёты в страховании", "Actuarial Calculations in Insurance"],
  ["Sug'urtada axborot texnologiyalari", "Информационные технологии в страховании", "Information Technology in Insurance"],
  ["Sug'urtada risk menejmenti", "Риск-менеджмент в страховании", "Risk Management in Insurance"],
  ["Sun'iy intellekt", "Искусственный интеллект", "Artificial Intelligence"],
  ["Sun'iy intellekt va jamiyat", "Искусственный интеллект и общество", "Artificial Intelligence and Society"],
  ["Tadbirkorlik faoliyatida biznes-rejalashtirish", "Бизнес-планирование в предпринимательской деятельности", "Business Planning in Entrepreneurship"],
  ["Tadbirkorlik va innovatsiyalar", "Предпринимательство и инновации", "Entrepreneurship and Innovation"],
  ["Tadqiqot usullar va ko'nikmalar", "Методы и навыки исследования", "Research Methods and Skills"],
  ["Tadqiqot usullari va ko'nikmalari", "Методы и навыки исследования", "Research Methods and Skills"],
  ["Talabalarni o'qitishda ishbilarmonlik o'yinlari", "Деловые игры в обучении студентов", "Business Games in Teaching Students"],
  ["Ta'minot zanjirini boshqarish", "Управление цепями поставок", "Supply Chain Management"],
  ["Tarmoq xavfsizligi", "Сетевая безопасность", "Network Security"],
  ["Tarmoqlarda tahlil xususiyatlari", "Особенности анализа в отраслях", "Specifics of Industry Analysis"],
  ["Tashabbusli byudjetlashitirish", "Инициативное бюджетирование", "Participatory Budgeting"],
  ["Tashkilotlarni boshqarish nazariyasi", "Теория управления организациями", "Theory of Organizational Management"],
  ["Tashqi iqtisodiy faoliyat tahlili", "Анализ внешнеэкономической деятельности", "Foreign Economic Activity Analysis"],
  ["Tashqi iqtisodiy faoliyatning tovar nomenklaturasi", "Товарная номенклатура внешнеэкономической деятельности", "Commodity Nomenclature of Foreign Economic Activity"],
  ["TIF da bojxonaning o'rni", "Роль таможни во внешнеэкономической деятельности", "The Role of Customs in Foreign Trade"],
  ["Tijorat va servis logistikasi", "Коммерческая и сервисная логистика", "Commercial and Service Logistics"],
  ["Tizimli menejment nazariyasi", "Теория системного менеджмента", "Systems Management Theory"],
  ["Tovarlarni elektron deklaratsiyalash", "Электронное декларирование товаров", "Electronic Declaration of Goods"],
  ["Turistik korxonalar faoliyati tahlili", "Анализ деятельности туристских предприятий", "Analysis of Tourism Enterprises"],
  ["Turizm geografiyasi", "География туризма", "Tourism Geography"],
  ["Turizm va mehmondo'stlikda tadbirkorlik", "Предпринимательство в туризме и гостеприимстве", "Entrepreneurship in Tourism and Hospitality"],
  ["Turizm xizmatlar bozori", "Рынок туристских услуг", "Tourism Services Market"],
  ["Turizm: nazariya va amaliyot", "Туризм: теория и практика", "Tourism: Theory and Practice"],
  ["Turizmda atrof muxit boshqaruvi", "Экологический менеджмент в туризме", "Environmental Management in Tourism"],
  ["Turizmda geoaxborot tizimlari", "Геоинформационные системы в туризме", "Geographic Information Systems in Tourism"],
  ["Turizmda loyihalar boshqaruvi", "Управление проектами в туризме", "Project Management in Tourism"],
  ["Turizmda sifat va xavfsizlik", "Качество и безопасность в туризме", "Quality and Safety in Tourism"],
  ["Veb tizimlari", "Веб-системы", "Web Systems"],
  ["Xalqaro audit", "Международный аудит", "International Auditing"],
  ["Xalqaro bank ishi", "Международное банковское дело", "International Banking"],
  ["Xalqaro bank ishi va moliya", "Международное банковское дело и финансы", "International Banking and Finance"],
  ["Xalqaro biznes", "Международный бизнес", "International Business"],
  ["Xalqaro biznes boshqaruvi", "Управление международным бизнесом", "International Business Management"],
  ["Xalqaro biznes huquqi", "Международное коммерческое право", "International Business Law"],
  ["Xalqaro biznes shartnomalari", "Международные коммерческие контракты", "International Business Contracts"],
  ["Xalqaro biznes va marketing muammolari", "Проблемы международного бизнеса и маркетинга", "Issues in International Business and Marketing"],
  ["Xalqaro inson resurslarini boshqarish", "Международное управление человеческими ресурсами", "International Human Resource Management"],
  ["Xalqaro iqtisodiy birlashmalar faoliyati", "Деятельность международных экономических объединений", "Activities of International Economic Associations"],
  ["Xalqaro iqtisodiy tashkilotlar", "Международные экономические организации", "International Economic Organizations"],
  ["Xalqaro iqtisodiyot", "Международная экономика", "International Economics"],
  ["Xalqaro iqtisodiyot (Advanced)", "Международная экономика (продвинутый курс)", "International Economics (Advanced)"],
  ["Xalqaro kapital bozori", "Международный рынок капитала", "International Capital Market"],
  ["Xalqaro logistika", "Международная логистика", "International Logistics"],
  ["Xalqaro marketing", "Международный маркетинг", "International Marketing"],
  ["Xalqaro menejment", "Международный менеджмент", "International Management"],
  ["Xalqaro moliya", "Международные финансы", "International Finance"],
  ["Xalqaro moliya bozori tahlili", "Анализ международного финансового рынка", "International Financial Market Analysis"],
  ["Xalqaro moliya institutlari", "Международные финансовые институты", "International Financial Institutions"],
  ["Xalqaro moliya munosabatlari", "Международные финансовые отношения", "International Financial Relations"],
  ["Xalqaro moliyaviy xavfsizlik va risklarni boshqarish", "Международная финансовая безопасность и управление рисками", "International Financial Security and Risk Management"],
  ["Xalqaro raqobat siyosati", "Международная конкурентная политика", "International Competition Policy"],
  ["Xalqaro savdo", "Международная торговля", "International Trade"],
  ["Xalqaro savdo huquqi va savdo amaliyoti", "Международное торговое право и торговая практика", "International Trade Law and Practice"],
  ["Xalqaro savdo va bojxona qonunchiligi", "Международная торговля и таможенное законодательство", "International Trade and Customs Law"],
  ["Xalqaro savdo va xalqaro shartnomalar", "Международная торговля и международные контракты", "International Trade and International Contracts"],
  ["Xalqaro statistika", "Международная статистика", "International Statistics"],
  ["Xalqaro tadbirkorlik", "Международное предпринимательство", "International Entrepreneurship"],
  ["Xalqaro tijorat ishi", "Международное коммерческое дело", "International Commerce"],
  ["Xalqaro transport koridorlari", "Международные транспортные коридоры", "International Transport Corridors"],
  ["Xalqaro turizm menejmenti", "Менеджмент международного туризма", "International Tourism Management"],
  ["Xalqaro turizm menegmenti", "Менеджмент международного туризма", "International Tourism Management"],
  ["Xalqaro valyuta-kredit munosabatlari", "Международные валютно-кредитные отношения", "International Monetary and Credit Relations"],
  ["Xalqaro valyuta operatsiyalari", "Международные валютные операции", "International Currency Operations"],
  ["Xizmatlar marketingi", "Маркетинг услуг", "Services Marketing"],
  ["Xorijiy investitsiya", "Иностранные инвестиции", "Foreign Investment"],
  ["Xorijiy investitsiyalarni jalb etish va boshqarish", "Привлечение иностранных инвестиций и управление ими", "Attracting and Managing Foreign Investment"],
  ["Xorijiy mamlakatlar g'aznachilik tizimi", "Казначейская система зарубежных стран", "Treasury Systems of Foreign Countries"],
  ["Xorijiy til", "Иностранный язык", "Foreign Language"],
  ["Xorijiy til (Ingliz tili)", "Иностранный язык (английский)", "Foreign Language (English)"],
  ["Xulq-atvor moliyasi", "Поведенческие финансы", "Behavioral Finance"],
  ["Xulq-atvor iqtisodiyoti", "Поведенческая экономика", "Behavioral Economics"],
  ["Xulq-atvor iqtisodiyoti va davlat siyosati", "Поведенческая экономика и государственная политика", "Behavioral Economics and Public Policy"],
  ["Yangi tahrirdagi O'zbekiston Respublikasi Konstitutsiyasi", "Конституция Республики Узбекистан в новой редакции", "The Constitution of the Republic of Uzbekistan (New Edition)"],
  ["Yashil iqtisodiyot", "Зелёная экономика", "Green Economy"],
  ["Yuridik shaxslarni soliqqa tortish", "Налогообложение юридических лиц", "Taxation of Legal Entities"],
];

function subjectKey(s) {
  return String(s || "").toLowerCase()
    .replace(/[`'ʻʼ’‘´?]/g, "")
    .replace(/[-–—_,.:;()/*]/g, " ")
    .replace(/\s+/g, " ").trim();
}

const SUBJECTS = new Map(SUBJECTS_RAW.map(([uz, ru, en]) => [subjectKey(uz), { ru, en }]));

// Номер части в конце названия: «-1», « 2», « 1,2», « I», « F1»
const PART_RE = /^(.*?)[\s\-]*((?:\d+(?:\s*,\s*\d+)*)|I{1,3}|F\d)\s*$/;

function translateSubject(name, lang) {
  if (!name || lang === "uz") return name;
  const full = SUBJECTS.get(subjectKey(name));
  if (full) return full[lang];
  const m = String(name).trim().match(PART_RE);
  if (m) {
    const base = SUBJECTS.get(subjectKey(m[1]));
    if (base) return `${base[lang]} ${m[2].replace(/\s*,\s*/g, ", ")}`;
  }
  return name;
}
